# fly.toml app configuration file generated for cubes on 2023-09-01T11:34:03+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cubes"
primary_region = "arn"

[build]

[[mounts]]
  source = "place"
  destination = "/data"

[[services]]
  protocol = "tcp"
  internal_port = 5173

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
