# fly.toml app configuration file generated for cubes on 2023-08-26T01:52:23+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cubes"
primary_region = "arn"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
